### ISSUE TITLE
Problen installing on Rasbian 9 (stretch) with python 3

### ISSUE THREAD

**Issue by NetForces** [PiSupply/PiJuice#179]
I have other code dependancies that require python3. Trying to install gives error about missing module `ConfigParser` while trying to install `python-urwid`

```
{14:15}~ ➭ apt-get install pijuice-base
Reading package lists... Done
Building dependency tree
Reading state information... Done
pijuice-base is already the newest version (1.3.3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up python-urwid (1.3.1-2) ...
Traceback (most recent call last):
  File "/usr/bin/pycompile", line 35, in <module>
    from debpython.version import SUPPORTED, debsorted, vrepr, \
  File "/usr/share/python/debpython/version.py", line 24, in <module>
    from ConfigParser import SafeConfigParser
ImportError: No module named 'ConfigParser'
dpkg: error processing package python-urwid (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of pijuice-base:
 pijuice-base depends on python-urwid; however:
  Package python-urwid is not configured yet.

dpkg: error processing package pijuice-base (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 python-urwid
 pijuice-base
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by NetForces** [comment]
I think I was able to install it this way:

```
pip3 install urwid
apt-get download pijuice-base
dpkg -i --ignore-depends=python-urwid pijuice-base_1.3.3_all.deb
```

I'm now able to run `python2 /usr/bin/pijuice_cli.py` and I get the battery status, so some parts are working.

**Comment by NetForces** [comment]
Looks like the pijuice service is not able to run

```
Jul 27 14:43:44 raspberrypi pijuice_sys.py[28363]: Traceback (most recent call last):
Jul 27 14:43:44 raspberrypi pijuice_sys.py[28363]:   File "/usr/bin/pijuice_sys.py", line 16, in <module>
Jul 27 14:43:44 raspberrypi pijuice_sys.py[28363]:     from pijuice import PiJuice
Jul 27 14:43:44 raspberrypi pijuice_sys.py[28363]: ImportError: No module named 'pijuice'
Jul 27 14:43:44 raspberrypi systemd[1]: pijuice.service: Control process exited, code=exited status=1
Jul 27 14:43:44 raspberrypi systemd[1]: pijuice.service: Unit entered failed state.
```

**Comment by NetForces** [comment]
I changed the systemd unit file so that it uses `python2` to start the process:

```
# /lib/systemd/system/pijuice.service
[Unit]
Description=PiJuice status service
After=network.target

[Service]
Type=idle
WorkingDirectory=/var/lib/pijuice/
ExecStart=/usr/bin/python2 /usr/bin/pijuice_sys.py
ExecStopPost=/usr/bin/python2 /usr/bin/pijuice_sys.py stop
Restart=always

[Install]
WantedBy=multi-user.target
```

Seems to be running now:

```
{14:46}~ ➭ systemctl status pijuice.service
● pijuice.service - PiJuice status service
   Loaded: loaded (/lib/systemd/system/pijuice.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-07-27 14:46:02 EDT; 1min 13s ago
 Main PID: 29773 (python2)
   CGroup: /system.slice/pijuice.service
           └─29773 /usr/bin/python2 /usr/bin/pijuice_sys.py

Jul 27 14:46:02 raspberrypi systemd[1]: Started PiJuice status service.
```

**Comment by NetForces** [comment]
Everything seems to work great with the above mods. Would just be nice to have a python3 compatible install.

**Comment by tvoverbeek** [comment]
@NetForces You can get a pure python3 installation with some manual copying/installing.
- The pijuice_sys.py, pijuice_gui.py and pijuice_cli.py code is python3 compatible.
- All of them import the pijuice module which is only installed for python2. However its code is also python3 compatible. Copy /usr/lib/python2.7/dist-packages/pijuice.py to one of the python3 module directories.
- pijuice_cli also needs urwid, which you installed via pip. However it is available in Raspbian as the python3-urwid package (`sudo apt-get install python3-urwid`).

My personal opinion is that in the future we should provide only pure python3 packages since python2 support will end and the next Raspbian will probably default to python3.

**Comment by shawaj** [comment]
Sounds like a reasonable thing to do

**Comment by tvoverbeek** [comment]
@FLYINGSC0T See my answer to @NetForces above.
I am assuming you have set python3 as your default python version.
The settings programs (pijuice_gui and pijuice_cli) and the service program all import the basic pijuice module. The deb package install only installs the basic pijuice module for Python2. Therefore all your programs fail because they cannot find the pijuice.py module.
However the pijuice.py code is Python3 compatible. It is installed in `/usr/lib/python2.7/dist-packages/pijuice.py`.
Copy this pijuice.py to one of the Python3 directories. I am on travel and do not have access to my RPis to check the python3 paths, but it should be something like /usr/lib/python3.x/dist-packages.
When pijuice.py is in the correct python3 package directory things should work.

Probably in the future a switch will be made to a python3 only installation

**Comment by shawaj** [comment]
Also I'm guessing the problem with finding the bootloader was due to the button SW3 not being held down properly when powering on.

Probably a good idea to upgrade to python 3 only pretty soon as this has happened a few times. @wikipedia555 what to you think?

**Comment by Luppie1975** [comment]
I'm experiencing the same problem.
Already copied /usr/lib/python2.7/dist-packages/pijuice.py TO /usr/lib/python3/dist-packages/pijuice.py

Checked that the pijuice service is started:
```
service pijuice status
● pijuice.service - PiJuice status service
   Loaded: loaded (/lib/systemd/system/pijuice.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2018-08-25 13:42:58 CEST; 4min 18s ago
 Main PID: 412 (pijuice_sys.py)
   CGroup: /system.slice/pijuice.service
           └─412 /usr/bin/python /usr/bin/pijuice_sys.py

Aug 25 13:42:58 domoticz.luppie.net systemd[1]: Started PiJuice status service.
```

When running pijuice_cli.py ans select Status it crashes:

```
Traceback (most recent call last):
  File "/usr/bin/pijuice_cli.py", line 1320, in <module>
    loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python2.7/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python2.7/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 592, in keypress
    *self.calculate_padding_filler(size, True)), key)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python2.7/dist-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python2.7/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python2.7/dist-packages/urwid/listbox.py", line 987, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/usr/lib/python2.7/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python2.7/dist-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/lib/python2.7/dist-packages/urwid/widget.py", line 464, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python2.7/dist-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python2.7/dist-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/bin/pijuice_cli.py", line 1255, in item_chosen
    callback()
  File "/usr/bin/pijuice_cli.py", line 65, in __init__
    self.main()
  File "/usr/bin/pijuice_cli.py", line 120, in main
    status_args = self.get_status()
  File "/usr/bin/pijuice_cli.py", line 83, in get_status
    gpio_info = "%.3fV, %.3fA, %s" % (io_voltage / 1000, io_current / 1000, status['powerInput5vIo'])
KeyError: 'powerInput5vIo'

```
When I select General i got this message : Unable to connect to device.

When I try to update the firmware : ./pijuiceboot 14 PiJuice-V1.2_2018_05_02.elf.binary

```
using address 14
Input file PiJuice-V1.2_2018_05_02.elf.binary
Starting bootloader
Starting bootloader old firmware
Sending get command
error receiving data -1

```

Any help is appreciated.

**Comment by shawaj** [comment]
Have you tried a full reset?

**Comment by Luppie1975** [comment]
I just did a full reset, with no luck.

**Comment by NetForces** [comment]
@Luppie1975 almost looks like you have something conflicting at address 14. Anything other than the PiJuice connected to your Pi ?

**Comment by Luppie1975** [comment]
I have 2x OneWire temperature sensors connected on GPIO4 and a smartmeter connected to GPIO14 & 15
Also a RFLink is connected but lts connected on USB

No other I2C are connected.

When running i2cdetect I see address 14 and 68 are used.

**Comment by NetForces** [comment]
What I would try is to remove all these device and only have the PiJuice and the Pi. If that works you can then start connecting one device after the other to see which ne is conflicting.

**Comment by Luppie1975** [comment]
Removed all peripherals and tried again, with the same result.
The Pi is running headless, so only a network cable is connected now, nothing else.

**Comment by NetForces** [comment]
@Luppie1975 You made sure your pi distro is up to date ?

```
apt-get -y update
apt-get -y upgrade
```

**Comment by Luppie1975** [comment]
Yes, I always update/upgrade before an install. 
My next step will be a clean install to rule out it's an issue with my current config.

**Comment by FLYINGSC0T** [comment]
Hi Luppie1975 - I had a great problem also installing the PiJuice. The Guy's at PiJuice insisted that I carried out another firmware update. I had already done this many times so I gave it my last try and it worked. Don't know why because I'm sure I did everything as before. The only thing different was that I held down SW3 during the entire bootup of the Pi. I had set Python 3 as the default as recommended by the PiJuice Guys and copied the relevant files into both the Python 2 and Python 3 directories for security. My setup is not headless and the GUI is installed. When I had the problems no LED's lit up on the PIJuice and there was no icon on the system tray although the PIJuice configuration menu did show up in the preferences menu. The PiJuice configuration screen all showed a COMMUNICATION_ERROR. Running the pijuicecli from the terminal and selecting "Status" crashed the progam. However, all works fine now and my setup has a Dragino LoRa GPS HAT sitting on top of the PiJuice. I'm no expert, but maybe if you install Rasbian Stretch with the GUI you will better see what is happening. Ensure all the relevant files are in the right place and before doing the firmware update ensure that the PiJuice service is stopped and try holding down SW3 during the bootup for longer. As I already mentioned I held down the SW3 button for the whole duration of the bootup of the Pi and it worked for me (the instructions say to hold SW3 for a few seconds but maybe this doesn't force the bootloader to load). I did revert to setting the default back to Python 2 as I have programs that are Python 2 compatable only and everything works fine so I hope you have success. Good luck !!

**Comment by tvoverbeek** [comment]
@Luppie1975 From your traceback of pijuice_cli.py and your attempt to use pijuiceboot it seems I2C communication is not working. Do you (accidentally) have disabled I2C?
A simple check is to see if `/dev/i2c-1` exists. Also try running `i2cdetect -y 1`. PiJuice should respond on addresses 0x14 and 0x68. If the PiJuice HAT has its id-eeprom at 0x50 the entry at 0x68 shows `'UU'` meaning the OS RTC driver is loaded.
All this assumes you are not using the original RPi model B (2012) which uses i2c bus 0 instead of 1.
To enable I2C use raspi-config.

**Comment by Luppie1975** [comment]
I never got it to work properly (since it is on my home Domotica system - reinstalling was no option), so I just used my PiJuice as a dumb batterypack not controlled by software.

Right now I've bought a new Raspberry Pi 3B+ (right now the latest model) and started from scratch.
Installed Raspbian Stretch Lite 
Version:April 2019
Release date:2019-04-08
Kernel version:4.14

At first boot I did:
raspi-config
(enable I2C, SSH, WiFi, set Hostname, Password, TimeZone, 1-Wire)
reboot
apt-get update
apt-get upgrade
apt-get dist-upgrade
rpi-update
reboot
apt-get install pijuice-base
pijuice_cli (No PiJuice found or Failed to use I2C bus - Check if I2C is enabled)
reboot
service pijuice start
service pijuice status

> ● pijuice.service - PiJuice status service
>    Loaded: loaded (/lib/systemd/system/pijuice.service; enabled; vendor preset: enabled)
>    Active: active (running) since Wed 2019-05-08 21:56:45 CEST; 1min 19s ago
>  Main PID: 530 (pijuice_sys.py)
>    CGroup: /system.slice/pijuice.service
>            └─530 /usr/bin/python3 /usr/bin/pijuice_sys.py

pijuice_cli  (No PiJuice found or Failed to use I2C bus - Check if I2C is enabled)
i2cdetect -y 1

>      0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
> 00:          -- -- -- -- -- -- -- -- -- -- -- -- --
> 10: -- -- -- -- 14 -- -- -- -- -- -- -- -- -- -- --
> 20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
> 30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
> 40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
> 50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
> 60: -- -- -- -- -- -- -- -- UU -- -- -- -- -- -- --
> 70: -- -- -- -- -- -- -- --
> 

Any help is appreciated, I'm getting the idea that I'm stuck with a defective PiJuice.

**Comment by tvoverbeek** [comment]
@Luppie1975 Strange.
i2cdetect shows the expected results. Even the simulated RTC in the PiJuice is recognized by the kernel (the 'UU'). So it must have successfully communicated with the PiJuice via I2C at boot.
Also pijuice_sys (the service) seems to work fine.
I suspect either some permission problem or some interference between 1-wire and I2C.
Can you try the following by running the python interpreter manually:
```
pi@rpi-pijuice:~ $ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pijuice import PiJuice
>>> pj=PiJuice(1,0x14)
Pijuice.py -- test version
>>> pj.status.GetStatus()
{'error': 'NO_ERROR', 'data': {'powerInput5vIo': 'NOT_PRESENT', 'isFault': True, 'isButton': False, 'powerInput': 'PRESENT', 'battery': 'CHARGING_FROM_IN'}}
>>> 
```
Maybe you get an error message which helps to localize the problem

**Comment by Luppie1975** [comment]
I've tried your suggestion with this output:

```
root@xxxxx:/home/pi# python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pijuice import PiJuice
>>> pj=PiJuice(1,0x14)
>>> Pijuice.py -- test version
  File "<stdin>", line 1
    Pijuice.py -- test version
                             ^
SyntaxError: invalid syntax
>>> pj.status.GetStatus()
{'data': {'battery': 'CHARGING_FROM_IN', 'powerInput5vIo': 'NOT_PRESENT', 'isButton': False, 'isFault': True, 'powerInput': 'PRESENT'}, 'error': 'NO_ERROR'}
>>>
```
I was not sure if Pijuice.py -- test version use to be some output in your example or that it is a command, so I entered it as a command.

However I managed to update the firmware now to PiJuice-V1.2_2018_05_02.elf.binary
But still with the same result that pijuice_cli cant find the PiJuice.

I also did the same with 1-wire disabled, but with the same result.

**Comment by tvoverbeek** [comment]
@Luppie1975 OK. I see you are running as root.
Your pj.status.GetStatus() output shows the PiJuice is working and answering via I2C.
The 'Pijuice.py -- test version' is output from my test version, Sorry about that, should have removed the line in my answer above.
Are you running pijuice_cli as root?
If I run it as root I also get the 'No PiJuice found or Failed to use I2C bus - Check if I2C is enabled' error message.
You are not supposed to run pijuice_cli as root. Try as user pi.

**Comment by teeso** [comment]
Hi, I'm trying to use my new pijuice_cli, I got a model A+ (raspberry) running updated and upgraded buster. I locate on i2c (witch is active) at address 5c. So from Python3 I was able to do the following lines:
from pijuice import PiJuice
pj=PiJuice(3,0x5c) 

no error, but >>> pj.status.GetStatus()
I got this 
{'error': 'DATA_CORRUPTED'}

also 

systemctl status pijuice
● pijuice.service - PiJuice status service
   Loaded: loaded (/lib/systemd/system/pijuice.service; disabled; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since Thu 2019-08-29 11:38:29 CEST; 7min ago
  Process: 2105 ExecStart=/usr/bin/pijuice_sys.py (code=exited, status=0/SUCCESS)
  Process: 2106 ExecStopPost=/usr/bin/pijuice_sys.py stop (code=exited, status=0/SUCCESS)
 Main PID: 2105 (code=exited, status=0/SUCCESS)

Aug 29 11:38:29 tsp systemd[1]: pijuice.service: Service RestartSec=100ms expired, scheduling restart.
Aug 29 11:38:29 tsp systemd[1]: pijuice.service: Scheduled restart job, restart counter is at 5.
Aug 29 11:38:29 tsp systemd[1]: Stopped PiJuice status service.
Aug 29 11:38:29 tsp systemd[1]: pijuice.service: Start request repeated too quickly.
Aug 29 11:38:29 tsp systemd[1]: pijuice.service: Failed with result 'start-limit-hit'.
Aug 29 11:38:29 tsp systemd[1]: Failed to start PiJuice status service.

sudo i2cdetect -y 3
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- 5c -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --             

any suggestion for making works?

**Comment by ChristopherRush** [comment]
@teeso Please see this issue here #327 On Raspbian Buster you need to load the old I2C drivers by adding `dtoverlay=i2c-bcm2708` to /boot/config.txt

**Comment by shawaj** [comment]
Closing this issue now. If anyone disagrees feel free to reply

**Comment by jkleiman** [comment]
Future people: I couldn't figure it out and then I took the battery out and put it back in and it started working. Woo!
