### ISSUE TITLE
PiJuice on Banana PI

### ISSUE THREAD

**Issue by ghenzinger** [PiSupply/PiJuice#245]
Hello everyone,

I wonder, if the PiJuice is working on different Platforms like Banana PI?
Has anyone experience on that?

Thank you
Gerald

**Comment by tvoverbeek** [comment]
I do not have any direct experience.
Since as far as I know most Banana Pis have a compatible 40 pin GPIO header.
The PiJuice only uses the power pins and the I2C.
Depending on the OS running on the Banana Pi you may need to tweak the software.
Since it is in Python, should not be a great problem. However it needs the I2C support.
Hope this helps

**Comment by ghenzinger** [comment]
Thank you! I will try!

**Comment by ChristopherRush** [comment]
Officially we only support the Raspberry Pi but thats not to say it won't work with other boards. See here for pinout - https://pinout.xyz/pinout/pijuice
