### ISSUE TITLE
What happens when I use RTC and Internet?

### ISSUE THREAD

**Issue by rossirm** [PiSupply/PiJuice#290]
Hi, dear guys!
Could you smo tell me what happens when I have set my RPi to use RTC of PiJuice and connect my system to Internet. Will Internet time influence the time from/on RTC?
Which time in which case does RPi use?
Thanks!

**Comment by tvoverbeek** [comment]
Assuming you mean using Raspbian with the Piuice HAT id-eeprom on address 0x50.
In that case Raspbian loads the ds1339 driver (i2c-rtc module) so the OS can access the RTC.
When you have an internet connection the timesyncd daemon synchronizes the OS time with the internet (in older versions ntp is used). It also copies the new OS time to the RTC (using UTC).
SInce the ds1339 has an alarm function the OS assumes it is in charge of the alarm and when copying the time to the RTC it resets the alarm. (The wakeup-flag in the PiJuice).
timesyncd (or ntp) resynchronizes the time and updates the RTC ca every 15 minutes.
The RPi always uses its own time.
On a PC running Linux the RTC time is copied to the OS time very early in the boot.
This does not happen on the RPi since at that time the I2C drivers are not loaded yet.
Therefore there is a fake hwclock which ensures the time continues where it was at the previous shutdown early in the boot.
