### ISSUE TITLE
Cannot access RTC when not in HAT configuration

### ISSUE THREAD

**Issue by neil-nn11** [PiSupply/PiJuice#292]
I have a project that I have tested with a Pi Zero plugged into a PiJuice (ie as a HAT) that accesses the RTC with no issues. 

However my end goal has space limitations and so I am trying to connect the Pi Zero and PiJuice with short (180mm)  jumper wires. The hardware documentation indicates I connect SDA and SCL on pins 3 and 5, plus I have 5v from pin 4 and ground from pin 6. The https://pinout.xyz/pinout/pijuice site also indicates I connect 3.3v. 

With these pins connected together when I issue 'sudo hwclock -s' I get 'Cannot access the hardware clock via any known method'. If I revert back to HAT configuration it works fine.
Am I missing a pin or is this some timing/voltage issue with the jumper wires?

**Comment by tvoverbeek** [comment]
Problem caused by RPi not being able to read the HAT eeprom on i2c bus 0.
When the RPi boots it accesses the HAT eeprom on pins 27 and 28 (BCM0 and BCM1).
2 solutions:
Solution 1: Connect 2 extra jumper wires to connect pins 27 and 28 between the RPi and the HAT.
Solution 2: If you do not want to connect the 2 extra jumper wires you can add the following line to /boot/config.txt: `dtoverlsy=i2c-rtc,ds1339` (uses both the RTC time and alarm functions) or `dtoverlay=i2c-rtc,ds1307` (uses only the RTC time function). You can check after boot with `i2c-detect -y 1` that address 0x68 is claimed by a driver when it shows 'UU'.
