### ISSUE TITLE
Hi All,

### ISSUE THREAD

**Issue by LuvSachdevaRFID** [PiSupply/PiJuice#352]
Hi All,
I am using 5000mAh of battery. I am trying to configure it from command Line Interface but as soon as click on Apply setting after i have made changes. It gives me a list of error.
Also, I try to configure through GUI but In PiHAT config. I am not able to see Battery options on top. Please advise. I can also put screenshots.Thanks

_Originally posted by @LuvSachdevaRFID in https://github.com/PiSupply/PiJuice/issues/351#issuecomment-519168206_

**Comment by tvoverbeek** [comment]
The error you see in pijuice_cli and the invisible battery profile in the GUI is caused by an invalid battery profile.
On the General tab of the HAT configuration in the GUI select the 'Reset to default configuration'. After confirmation the LEDs will flash red/blue for a while.
Restart the GUI and the battery tab should be there with the default BP7X_1820 profile selected.
Now select the PJLIPO_5000 from the drop down menu and press the Apply button (Note under Buster the window is too small to show the Apply button. Enlarge it by dragging the bottom.).
