### ISSUE TITLE
Pi 400 does not boot up

### ISSUE THREAD

**Issue by zakelchami** [PiSupply/PiJuice#949]
Hi, 

I am trying to connect the PiJuice to the Raspberry Pi 400, when i turn on the pi using an external powersource, the Pi turns on normally, if i disconnect the external power source, the pi will stay on through the  pijuice. 

If i try to turn on the Pi using the piJuice, it does not power on. Please advise for a solution.

I found a link that sort of describes what is happening.
https://www.hackster.io/news/raspberry-pi-400-design-change-puts-an-end-to-battery-power-gpio-add-on-boards-770826a23ed9

**Comment by tvoverbeek** [comment]
Yes, that link explains that powering the pi 400 from the GPIO side (which is what happens if you try to turn on from the PiJuice) it is not going to work. The PiJuice cannot be used in this way for the Pi 400.
However UPS functionaiity (Pi keeps running when external power disappears) is still working (as you described).
